In [1]:
import numpy as np

# Create an array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)

# Create an array of zeros
arr2 = np.zeros((3, 3))
print("Array of zeros:\n", arr2)

# Create an array of ones
arr3 = np.ones((2, 4))
print("Array of ones:\n", arr3)

# Create an array with a range of values
arr4 = np.arange(10, 20)
print("Array with range of values:", arr4)

# Create an array with values evenly spaced
arr5 = np.linspace(0, 1, 5)
print("Array with evenly spaced values:", arr5)


Array from list: [1 2 3 4 5]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with range of values: [10 11 12 13 14 15 16 17 18 19]
Array with evenly spaced values: [0.   0.25 0.5  0.75 1.  ]
