In [1]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed_arr = np.transpose(arr)
print("Original array:\n", arr)
print("Transposed array:\n", transposed_arr)


Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
