In [1]:
import numpy as np

# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a file
np.save('array.npy', arr)
print("Array saved to 'array.npy'")

# Load the array from the file
loaded_arr = np.load('array.npy')
print("Loaded array:\n", loaded_arr)

# Save the array to a text file
np.savetxt('array.txt', arr, delimiter=',')
print("Array saved to 'array.txt'")

# Load the array from the text file
loaded_txt_arr = np.loadtxt('array.txt', delimiter=',')
print("Loaded array from text file:\n", loaded_txt_arr)

Array saved to 'array.npy'
Loaded array:
 [[1 2 3]
 [4 5 6]]
Array saved to 'array.txt'
Loaded array from text file:
 [[1. 2. 3.]
 [4. 5. 6.]]
